requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "DBD::mysql";
requires "Starman";
requires "Plack::Session";

requires 'Devel::NYTProf';
requires 'Devel::KYTProf';
requires 'Starlet';
requires 'Server::Starter';
requires 'Redis::Fast';

requires 'Cache::Memcached::Fast';
requires 'Sereal';
